### PR TITLE
fix(bugs): all coroutines are asleep - deadlock!

### PR DESCRIPTION
**Pull request by littlezo**
===================================================================
 [FATAL ERROR]: all coroutines (count: 2) are asleep - deadlock!

===================================================================

 [Coroutine-1]
--------------------------------------------------------------------
#0 /xx/vendor/hyperf/engine/src/Channel.php(41): Swoole\Coroutine\Channel->pop()
#1 /xx/vendor/friendsofhyperf/sentry/src/HttpClient/HttpClient.php(83): Hyperf\Engine\Channel->pop()
#2 [internal function]: FriendsOfHyperf\Sentry\HttpClient\HttpClient->FriendsOfHyperf\Sentry\HttpClient\{closure}()

### CODE REVIEW

**Comment by huangdijia** [comment]
可以给一下复现代码吗？

**Comment by littlezo** [comment]
配合 hyperf/watcher 组件 重载时 触发死锁

**Comment by littlezo** [comment]
> 可以给一下复现代码吗？

配合 hyperf/watcher 组件 重载时 触发死锁

**Comment by littlezo** [comment]
> 可以给一下复现代码吗？

[https://github.com/hyperf/hyperf/pull/7084](hyperf/hyperf#7084)

**Comment by huangdijia** [comment]
我看看

**Pull request closed without merging**
